### ISSUE TITLE
Can't generate opx cps document

### ISSUE THREAD

**Issue by jimmymagemtek** [open-switch/opx-cps#102]
Hi 
I tried to get the cps document according to the web site:

API documentation
The CPS API is documented through Doxygen. To generate CPS Doxygen content, at the top level of your source directory (one level underneath opx-cps), run the opx-cps/doc/cps_gen_doc.sh command.
=================================================================================

but got the following error:

root@debian:/home/jimmy/opx/opx-cps/doc# ./cps_gen_doc.sh 
Cannot find cps_api directory

Any suggestion is appreciated.

Jimmy

**Comment by jeff-yin** [comment]
This is likely due to a merge/sync issue. The `cps-api` directory in OPX should just be `cps`.

**Comment by rakeshdatta** [comment]
@jimmymagemtek  I guess the documentation did confuse you.
You should run it in the directory where opx-cps repository exists.

Plz try it and let me know.

e.g. 

```
rdatta@netlogin-eqx-01:/neteng/rdatta/github-issues/opx-cps/84$ opx-cps/doc/cps_gen_doc.sh
Notice: Output directory `workspace/cps-api-doc/c-cpp-doc' does not exist. I have created it for you.
Parsing layout file opx-cps/doc/layout_c_cpp.xml...
Searching for include files...
Searching for example files...
Searching for images...

```

**Comment by jimmymagemtek** [comment]
Hi Jeff,
Thanks for the information, but I got the same result as below,

root@debian:/home/jimmy/opx/opx-cps# ./doc/cps_gen_doc.sh 
Cannot find cps_api directory
root@debian:/home/jimmy/opx/opx-cps# cd ..
root@debian:/home/jimmy/opx# cd ..
root@debian:/home/jimmy# find -name cps_api
root@debian:/home/jimmy# 


Where should I acquire the "cps_api" directory ?
Thanks again.
Jimmy

**Comment by rakeshdatta** [comment]
@jimmymagemtek 

As I replied earlier, you need to execute it 'at the top level of your source directory'. i.e The directory where your opx-cps directory resides in.

In your case please run the command inside: '/home/jimmy/opx/'.


It is not looking for cps-api directory. It is just a error print, where you should read 'cps-api' as 'opx-cps'.

**Comment by jimmymagemtek** [comment]
Hi Jeff,
Thanks. I see the html files under opx/workspace.

Jimmy
