### ISSUE TITLE
CPS Get OID Call On S4000 Platform Running Out Of Memory Before Listing 16K Routes

### ISSUE THREAD

**Issue by kmarisetty** [open-switch/opx-cps#111]
On a **S4048** platform with OPX Version **3.1.0**, we execute the following command:
"**cps_get_oid.py base-route/obj/entry base-route/obj/entry/af=2 | grep   -E "78{1}[64-66]{1}" \| wc -l**"

This command causes a "out of memory error" and never gets to list details for each of the 16K routes in the CPS table. Below are the logs from the S4048 platform regarding this issue:

root@TR1:~# cps_get_oid.py base-route/obj/entry base-route/obj/entry/af=2 | grep   -E "78{1}[64-66]{1}" \| wc -l
_(1 minute later)_
[325675.345083] **Out of memory: Kill process 21185** (cps_get_oid.py) score 414 or sacrifice child
[325675.354551] **Killed process 21185** (cps_get_oid.py) total-vm:1167932kB, anon-rss:864628kB, file-rss:1252kB, shmem-rss:0kB

In show IP BGP summary command executed in vtysh shell, it is confirmed that there are 16,000 prefixes on the S4048 platform for each of the neighbors:

root@TR1:~# vtysh -c "show ip bgp sum"

IPv4 Unicast Summary:
BGP router identifier 100.0.3.1, local AS number 64801 vrf-id 0
BGP table version 261198
RIB entries 32039, using 5006 KiB of memory
Peers 2, using 41 KiB of memory

Neighbor        V         AS MsgRcvd MsgSent   TblVer  InQ OutQ  Up/Down State/PfxRcd
100.0.2.1       4      64801   78441   78335        0    0    0 00:00:07                      16010
100.0.2.2       4      64801   78513   78410        0    0    0 00:00:08                      16010

Total number of neighbors 2

Thanks
Ketan Marisetty

**Comment by GarrickHe** [comment]
@kmarisetty ,

Can you sure your system's configuration and also the output for this command:
`free -h`

thanks,
Garrick

**Comment by GarrickHe** [comment]
Update - Got testbed info from Ketan. Investigating...

**Comment by GarrickHe** [comment]
The s4048 only has 2GB of ram and is running out of memory due to the way cps_get_oid.py works. I provided a workaround for this issue:

```
cps_get_oid.py base-route/obj/entry base-route/obj/entry/af=2​ >& bgp_tmp.log
grep -E "78{1}[64-66]{1}" bgp_tmp.log | wc -l
```

Until we enable swap-space or ZRAM on OPX.
