### ISSUE TITLE
yang parser fails if model augments its own nodes

### ISSUE THREAD

**Issue by dimbleby** [open-switch/opx-cps#33]
with the following stack:

```
Traceback (most recent call last):
  File "/usr/lib/opx/py/yin_parser.py", line 34, in <module>
    yf = yin_model.CPSYangModel(d)
  File "/usr/lib/opx/py/yin_model.py", line 155, in __init__
    self.model = ctx['file-finder'].load(self.filename)
  File "/usr/lib/opx/py/yin_model.py", line 93, in load
    return self.get_parsed_yin(yang_file, prefix)
  File "/usr/lib/opx/py/yin_model.py", line 57, in get_parsed_yin
    _cps_parser.walk()
  File "/usr/lib/opx/py/yin_cps.py", line 165, in walk
    self.handle_augments(self.root_node, self.module.name() + ':')
  File "/usr/lib/opx/py/yin_cps.py", line 243, in handle_augments
    _key_model = self.context['loader'].yin_map[self.context['model-names'][__ns]]
KeyError: 'bgp'
```

We're trying to find the model that's being augmented, but it's the current model and so the data structure isn't yet ready.

I've worked around this by commenting out [this line](https://github.com/open-switch/opx-cps/blob/554c317ccbef3890acfb2d5fb9b0474517f7ed8d/scripts/lib/yang_tools/py/yin_cps.py#L165), and instead calling

```python
_cps_parser.handle_augments(_cps_parser.root_node, _cps_parser.module.name() + ':')
```

from [here](https://github.com/open-switch/opx-cps/blob/554c317ccbef3890acfb2d5fb9b0474517f7ed8d/scripts/lib/yang_tools/py/yin_model.py#L61).

But that seems kinda ugly, probably there's a better way.

I'm trying to establish whether I'm allowed to share with you the yang model on which I found this problem.  (I suspect that the answer will be 'no')
* If 'yes' then I'll attach it.  
* Else, if you need me to create a sample file that reproduces this, then please say so.

**Comment by c-wichmann** [comment]
Thanks very much,  If you could provide just an example that would be perfect.  No need to provide the original model.

**Comment by dimbleby** [comment]
This should do it:

```
module example {

    namespace "http://www.example.com";
    prefix "example";

    list foo {
        key "bar";

        leaf bar {
            type uint32;
        }
    }

    augment "/example:foo" {
         leaf baz {
            type uint32;
         }
    }
}
```

**Comment by c-wichmann** [comment]
Ok, that is fine.  The other items are resolved and should be pushed soon - and we will have this resolved at the same time.

**Comment by c-wichmann** [comment]
A few tweaks had to be made for this one since the  keys within the augment were being searched for at the time of the augment processing so we could track it easier when it comes to writing out the actual data.

**Comment by jeff-yin** [comment]
I believe this issue has since been resolved in the latest version of OPX. If not, please re-open (or open a new one).
