### ISSUE TITLE
yang parser fails to disambiguate nodes

### ISSUE THREAD

**Issue by dimbleby** [open-switch/opx-cps#34]
[These lines](https://github.com/open-switch/opx-cps/blob/554c317ccbef3890acfb2d5fb9b0474517f7ed8d/scripts/lib/yang_tools/py/yin_cps.py#L360-L363) can result in two different nodes having the same `n_path`, causing me much confusion.

I hit this on a model where a node contains both `config true;` and `container config { ... }`

As in #33, I may not be able to share the model on which I discovered this - let me know if you need me to construct an example.

**Comment by c-wichmann** [comment]
Thanks - that description was fine.  Can patch it.  Would you mind waiting another week (will be in the latest update) or do you need it earlier?

**Comment by dimbleby** [comment]
No need to hurry on my account!

**Comment by c-wichmann** [comment]
The config node and config false have been handled along with ignoring quite a few useless nodes.  This will go into the next merge.

**Comment by jeff-yin** [comment]
Next merge has occurred so this should be fixed. Closing the issue for now. If you run into it again, please open a new issue.
