### ISSUE TITLE
yang parser generates conflicting typedefs

### ISSUE THREAD

**Issue by dimbleby** [open-switch/opx-cps#36]
The model below results in a header file with conflicting definitions for EXAMPLE_FOO_t: 

* a typedef corresponding to the input typedef
* an enum corresponding to the list definition

(Of course I hit this on a real model, this is just a reduced testcase).

```
module example {

  namespace "http://example.com";

  prefix example;

  typedef foo {
    type uint32;
  }

  list foo {
    key "bar";

    leaf bar {
      type uint32;
    }
  }
}
```

Compiling the output gives this error:

```
In file included from opx/example.cpp:4:0:
opx/example.h:42:3: error: conflicting declaration 'typedef enum EXAMPLE_FOO_t EXAMPLE_FOO_t'
 } EXAMPLE_FOO_t;
   ^
opx/example.h:34:18: note: previous declaration as 'typedef uint32_t EXAMPLE_FOO_t'
 typedef uint32_t EXAMPLE_FOO_t;
                  ^
```

**Comment by dimbleby** [comment]
The above might be an over-simplification of the original problem as I'm not quite certain that it is valid to have the duplicate `foo`s above.  

Here's an example closer to my original model that produces the same problem by generating duplicate `foo-bar`s:

```
module example {

  namespace "http://example.com";

  prefix example;

  typedef foo-bar { type uint32; }

  list foo {
    key "name";
    leaf name { type string; }
    list bar {
      key "number";
      leaf number { type uint32; }
    }
  }
}
```

**Comment by c-wichmann** [comment]
Hmm.. yes.. the list "bar" and the typedef will conflict - in the C header.  Should be able to resolve this in the next update.

**Comment by c-wichmann** [comment]
The update was made and you should find that the case you mention is resolved.
