### ISSUE TITLE
Loopback interface configuration is not reported

### ISSUE THREAD

**Issue by dimbleby** [open-switch/opx-cps#40]
If I query `dell-base-if-cmn/if/interfaces/interface`, loopback interfaces are not reported.

Loopback interfaces are reported at `dell-base-if-cmn/if/interfaces-state/interface`, though so far as I can see there's no way of identifying them as such.  (Edit - now reported at #41)

Therefore to find loopback interfaces I have no better method than: 
* query both of the above
* look for interfaces that are in state but not configuration
* guess that those are loopback interfaces
* hope for the best

I'm using OPX 2.1

**Comment by GarrickHe** [comment]
Hello @dimbleby ,
Since this issue is related to #41 I'll take a look at this one as well.

Thanks,
Garrick

**Comment by atanu-mandal** [comment]
This is fixed, the change will be sent out for code review shortly.

**Comment by atanu-mandal** [comment]
Review requests
https://review.openswitch.net/#/c/14505/
https://review.openswitch.net/#/c/14504/

**Comment by atanu-mandal** [comment]
The fixes are merged.
