### ISSUE TITLE
CPS does not report all fields from YANG models

### ISSUE THREAD

**Issue by dimbleby** [open-switch/opx-cps#41]
Of particular interest to us right now are

* `dell-base-if-cmn/if/interfaces-state/interface/type` (cf #40)
* `dell-base-if-cmn/if/interfaces/interface/description` (less important but would be nice to have)

**Comment by jeff-yin** [comment]
Yeah, that's the first thing we're going to investigate. Lots of updates to CPS between version 2.1.0 and version 2.2.0.

If these issues are still seen in 2.2 then we're going to need to devise and roll out some fixes.

**Comment by GarrickHe** [comment]
Hello @dimbleby,

I'll look into this and keep you posted.

Thanks,
Garrick

**Comment by GarrickHe** [comment]
Hello @dimbleby,
Those two fields are also not reported on 2.2.0. I'm assuming you use 'observed' as your qualifier. I'll do some more digging to find out why it's not reported (I don't see a reason why it shouldn't, but maybe there is). If there is no reason why, I'll add that in as the output for the query. Will keep you posted.

**Comment by atanu-mandal** [comment]
For the "description" attribute, a textual description of the interface should be available (which is optional) so that it can print the output.

**Comment by atanu-mandal** [comment]
Quick update --this is fixed, the change will be sent out for code review shortly.

**Comment by atanu-mandal** [comment]
As mentioned above "description" is optional, so not treated as priority item.

**Comment by atanu-mandal** [comment]
https://review.openswitch.net/#/c/14496/

**Comment by atanu-mandal** [comment]
Fix is merged.
