### ISSUE TITLE
Interface state is reported in duplicate

### ISSUE THREAD

**Issue by dimbleby** [open-switch/opx-cps#42]
When I query `dell-base-if-cmn/if/interfaces-state/interface`, I see all interfaces reported twice.

**Comment by Tejaswi-Goel** [comment]
Hello,

I'll look into this and keep you posted.

-Tejaswi

**Comment by atanu-mandal** [comment]
Quick update --this is fixed, the change will be sent out for code review shortly.

**Comment by jeff-yin** [comment]
Here's the review request:
https://review.openswitch.net/#/c/14496/

**Comment by atanu-mandal** [comment]
Fix is merged.
