### ISSUE TITLE
Can't delete loopback interface

### ISSUE THREAD

**Issue by dimbleby** [open-switch/opx-cps#45]
Here's an attempt to delete a loopback interface:

```
$ ip link show lo4
39: lo4: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1632 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/ether 02:a5:ea:e0:b1:a6 brd ff:ff:ff:ff:ff:ff

$ sudo nas_intf_set.py -o delete lo4
delete
lo4
ianaift:ethernetCsmacd
None
None

$ ip link show lo4
39: lo4: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1632 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/ether 02:a5:ea:e0:b1:a6 brd ff:ff:ff:ff:ff:ff
```

As you can see, it just isn't deleted.

I see this in syslog at the time, which I suppose is a clue:

```
Jan 24 10:24:25 opx_vm opx_nas_daemon[543]: [INTERFACE:NAS-COM-INT-GET], Get request handler was not registered for obj Category 0 and type 4
```

I imagine that this is related to #40 and #43?

**Comment by GarrickHe** [comment]
Hello @dimbleby,

I'll look into this issue. Will keep you updated.

Thanks,
Garrick

**Comment by atanu-mandal** [comment]
We need to fix the python utility script to pass the type as loopback for delete operation.

We can use following command to delete this.
e.g. 
cps_set_oid.py -qua target -oper action dell-base-if-cmn/set-interface dell-base-if-cmn/set-interface/input/operation=2 if/interfaces/interface/name=lo4
if/interfaces/interface/type=ianaift:softwareLoopback

**Comment by atanu-mandal** [comment]
Please try the above utility to delete the loopback interface and let me know if you see any issues.

**Comment by dimbleby** [comment]
Yes, that does the trick - thanks!

**Comment by atanu-mandal** [comment]
Great. I am closing this issue since we have the solution.
