### ISSUE TITLE
L3ipvlan support

### ISSUE THREAD

**Issue by james-jra** [open-switch/opx-cps#46]
Are L3ipvlan type interfaces currently supported?

I have been unable to create interfaces of this type:
* I modified the vlan configuration script in the opx-nas-interface repository (https://github.com/open-switch/opx-nas-interface/blob/master/scripts/bin/cps_config_vlan.py) to use l3ipvlan type interfaces instead of l2vlan.
* This caused the transaction to fail and no interface to come up.
* I can create l2vlan type interfaces as expected

Note, I'm currently using v2.1

**Comment by atanu-mandal** [comment]
ianaift:l3vlan type is not yet supported during vlan creation.

**Comment by james-jra** [comment]
Do you plan to support it in the near future?

**Comment by atanu-mandal** [comment]
“ianaift:l3vlan” is not honored, when you configure IP address to the vlan interface it becomes l3 interface.

We are planning to cleanup  l3vlan option from below yang file which causes the confusion.
https://github.com/open-switch/opx-base-model/blob/master/yang-models/dell-interface.yang

**Comment by atanu-mandal** [comment]
Closing this based on above comments.
