### ISSUE TITLE
CPS does not report interface type for VLAN interfaces

### ISSUE THREAD

**Issue by james-jra** [open-switch/opx-cps#47]
Similar to #41 , but I think it's specific to VLAN interfaces

Missing field is `dell-base-if-cmn/if/interfaces/interface/type`

However, interestingly, I can query interface configuration by type, and the VLAN interface is returned correctly, but still missing the type field:

```
opxUser@opx_vm:~$ sudo cps_get_oid.py dell-base-if-cmn/if/interfaces/interface if/interfaces/interface/type=ianaift:l2vlan

Key: 1.19.44.2883617.2883612.2883613.
dell-base-if-cmn/if/interfaces/interface/if-index = 54
dell-if/if/interfaces/interface/phys-address = 08:00:27:d3:70:29
base-if-vlan/if/interfaces/interface/id = 100
if/interfaces/interface/name = br100
dell-if/if/interfaces/interface/vlan-type = 1
dell-if/if/interfaces/interface/learning-mode = 1
dell-if/if/interfaces/interface/mtu = 1532
if/interfaces/interface/enabled = 1
```
Note: the same query by type for interface state does not return anything, but this may be a separate issue, related to #43 
```
sudo cps_get_oid.py observed dell-base-if-cmn/if/interfaces-state/interface if/interfaces-state/interface/type=ianaift:l2vlan
```

**Comment by atanu-mandal** [comment]
The code path is bit different for vlan interface. We will add the "type" attribute.

**Comment by atanu-mandal** [comment]
Quick update --this is fixed, the change will be sent out for code review shortly.

**Comment by atanu-mandal** [comment]
"type" is available in the output when dell-base-if-cmn/if/interfaces/interface is queried.  Fix is merged.
