### ISSUE TITLE
VLAN interface state oper-status and admin-status always "down"

### ISSUE THREAD

**Issue by james-jra** [open-switch/opx-cps#48]
Regardless of the bridge interface state reported in `ip link`, CPS always reports the VLAN bridge interface as down.
* `if/interfaces-state/interface/oper-status = 1`
* `if/interfaces-state/interface/admin-status = 1`

More detailed trace follows:
```
# VLAN interface is down
opxUser@opx_vm:~$ sudo ip link set dev br100 down
opxUser@opx_vm:~$ ip link show br100
54: br100: <BROADCAST,MULTICAST,PROMISC> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default
    link/ether 08:00:27:d3:70:29 brd ff:ff:ff:ff:ff:ff

# CPS reports down
opxUser@opx_vm:~$ sudo cps_get_oid.py observed dell-base-if-cmn/if/interfaces-state/interface
...
if/interfaces-state/interface/admin-status = 1
dell-if/if/interfaces-state/interface/duplex = 1
dell-if/if/interfaces-state/interface/auto-negotiation = 0
if/interfaces-state/interface/if-index = 54
if/interfaces-state/interface/oper-status = 1
dell-if/if/interfaces-state/interface/oui = 6976381
dell-if/if/interfaces-state/interface/fec = 2
dell-if/if/interfaces/interface/mtu = 1532
if/interfaces-state/interface/name = br100
if/interfaces/interface/enabled = 0

# VLAN interface is up
opxUser@opx_vm:~$ sudo ip link set dev br100 up
opxUser@opx_vm:~$ ip link show br100
54: br100: <NO-CARRIER,BROADCAST,MULTICAST,PROMISC,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default
    link/ether 08:00:27:d3:70:29 brd ff:ff:ff:ff:ff:ff

# CPS still reports down
opxUser@opx_vm:~$ sudo cps_get_oid.py observed dell-base-if-cmn/if/interfaces-state/interface
...
if/interfaces-state/interface/admin-status = 1
dell-if/if/interfaces-state/interface/duplex = 1
dell-if/if/interfaces-state/interface/auto-negotiation = 0
if/interfaces-state/interface/if-index = 54
if/interfaces-state/interface/oper-status = 1
dell-if/if/interfaces-state/interface/oui = 6976381
dell-if/if/interfaces-state/interface/fec = 2
dell-if/if/interfaces/interface/mtu = 1532
if/interfaces-state/interface/name = br100
if/interfaces/interface/enabled = 1
```

**Comment by atanu-mandal** [comment]
We will check and get back on this.

**Comment by atanu-mandal** [comment]
"interfaces-state" is not provided for VLAN interface. We have incorporated the changes to have the required information as asked in #52 through "interfaces" object. 
In that context "if/interfaces/interface/enabled" attribute is suggested to decide on "if/interfaces-state/interface/admin-status" and "if/interfaces-state/interface/oper-status" for VLAN interface. 
Hope that helps.

**Comment by mcallisterjp** [comment]
Atanu,

This is fine for the admin-status concept, but doesn't really reflect the oper-status concept well — it seems strange to report a VLAN that is enabled but contains only oper-down ports as "up". Are there any plans to integrate this operational state into the VLAN interface entry?

**Comment by atanu-mandal** [comment]
We are working on to provide if/interfaces-state/interface/oper-status for VLAN interface that would reflect the oper state of corresponding bridge interface.

**Comment by jeff-yin** [comment]
Will be fixed in 3.0.0

**Comment by GarrickHe** [comment]
Update - UT completed, fix is in code-review.

**Comment by jeff-yin** [comment]
Fixed by https://github.com/open-switch/opx-nas-interface/pull/34
