### ISSUE TITLE
Support for VLAN Sub-interface

### ISSUE THREAD

**Issue by james-jra** [open-switch/opx-cps#50]
I saw you added VLAN sub-interfaces to the [dell-base-interface-common.yang](https://github.com/open-switch/opx-base-model/blob/master/yang-models/dell-base-interface-common.yang) model.

However they don't seem to be accessible at all via CPS.
They are currently a requirement for our ability to configure tagged sub-ports on VLANs.
Am I doing something wrong, or are they unsupported for querying and configuration via CPS?

sample trace:
```
root@OPX:/usr/bin# ip link add link e101-026-0 name e101-026-0.100 type vlan id 100
root@OPX:/usr/bin# ip link | tail -n 2
44: e101-026-0.100@e101-026-0: <BROADCAST,MULTICAST,M-DOWN> mtu 1500 qdisc noop state DOWN mode DEFAULT group default
    link/ether 34:17:eb:2c:d7:65 brd ff:ff:ff:ff:ff:ff

# Querying by type returns nothing
root@OPX:/usr/bin# sudo cps_get_oid.py dell-base-if-cmn/if/interfaces/interface if/interfaces/interface/type=base-if:vlanSubInterface

# Querying all config or state and searching for "026" only returns results from the original interface
# And viewing the full output confirms the subinterface is not present
root@OPX:/usr/bin# sudo cps_get_oid.py dell-base-if-cmn/if/interfaces/interface | grep 026
if/interfaces/interface/name = e101-026-0

root@OPX:/usr/bin# sudo cps_get_oid.py -qua observed dell-base-if-cmn/if/interfaces-state/interface | grep 026
if/interfaces-state/interface/name = e101-026-0
if/interfaces-state/interface/name = e101-026-0 # (duplicates as per https://github.com/open-switch/opx-cps/issues/42)
```

**Comment by atanu-mandal** [comment]
The VLAN sub interface type(i.e. vlanSubInterface) is not handled in current OPX 2.2.0 code base and the functionality is being developed in-house (would be part of later OPX main release).

Given that, we should be able to handle the requirement to add/query tagged interfaces to a VLAN.

Configuring tagged ports through Linux utilities
-----------------------------------------------------
root@OPX:~# brctl addbr br200
root@OPX:~# ip addr flush dev e101-020-0
root@OPX:~# ip link add link e101-020-0 name e101-020-0.200 type vlan id 200
root@OPX:~# brctl addif br200 e101-020-0.200

root@OPX:~# brctl show
bridge name     bridge id               STP enabled     interfaces
br200           8000.90b11cf49d23       no              **e101-020-0.200**

root@OPX:~# cps_get_oid.py dell-base-if-cmn/if/interfaces/interface | grep 020
**dell-if/if/interfaces/interface/tagged-ports = e101-020-0**
if/interfaces/interface/name = e101-020-0

root@OPX:~# opx-switch-shell "vlan show"
vlan 1  ports none (0x0000000000000000000000000000000000000000000000000000000000000000), untagged none (0x0000000000000000000000000000000000000000000000000000000000000000) MCAST_FLOOD_UNKNOWN
**vlan 200        ports xe64 (0x0000000000000000000000000000000000000000000000020000000000000000), untagged none (0x0000000000000000000000000000000000000000000000000000000000000000)** MCAST_FLOOD_UNKNOWN
vlan 4095       ports xe (0x00000000000000000000000000000000000001fffffffffffffffffffffffffe), untagged xe (0x00000000000000000000000000000000000001fffffffffffffffffffffffffe) MCAST_FLOOD_UNKNOWN

root@OPX:~# cps_config_vlan.py --show
Key: 1.19.44.2883617.2883612.2883613.
dell-base-if-cmn/if/interfaces/interface/if-index = 38
dell-if/if/interfaces/interface/phys-address = 90:b1:1c:f4:9d:23
base-if-vlan/if/interfaces/interface/id = 200
if/interfaces/interface/name = br200
dell-if/if/interfaces/interface/vlan-type = 0
dell-if/if/interfaces/interface/learning-mode = 1
dell-if/if/interfaces/interface/mtu = 1532
if/interfaces/interface/enabled = 0
**dell-if/if/interfaces/interface/tagged-ports = e101-020-0**

Configuring tagged ports through CPS utilities
---------------------------------------------------

root@OPX:~# cps_config_vlan.py --add --id 100 --vlantype 1 --port e101-001-0 --t
Success

root@OPX:~# brctl show
bridge name     bridge id               STP enabled     interfaces
br100           8000.90b11cf49d23       no              **e101-001-0.100**

root@OPX:~# cps_get_oid.py dell-base-if-cmn/if/interfaces/interface | grep 001
**dell-if/if/interfaces/interface/tagged-ports = e101-001-0**
if/interfaces/interface/name = e101-001-0


root@OPX:~# opx-switch-shell -c "vlan show"

vlan 1  ports none (0x0000000000000000000000000000000000000000000000000000000000000000), untagged none (0x0000000000000000000000000000000000000000000000000000000000000000) MCAST_FLOOD_UNKNOWN
**vlan 100        ports xe0 (0x0000000000000000000000000000000000000000000000000000000000000002), untagged none (0x0000000000000000000000000000000000000000000000000000000000000000)** MCAST_FLOOD_UNKNOWN
vlan 4095       ports xe (0x00000000000000000000000000000000000001fffffffffffffffffffffffffe), untagged xe (0x00000000000000000000000000000000000001fffffffffffffffffffffffffe) MCAST_FLOOD_UNKNOWN

root@OPX:~# cps_config_vlan.py --show
Key: 1.19.44.2883617.2883612.2883613.
dell-base-if-cmn/if/interfaces/interface/if-index = 36
dell-if/if/interfaces/interface/phys-address = 90:b1:1c:f4:9d:23
base-if-vlan/if/interfaces/interface/id = 100
if/interfaces/interface/name = br100
dell-if/if/interfaces/interface/vlan-type = 1
dell-if/if/interfaces/interface/learning-mode = 1
dell-if/if/interfaces/interface/mtu = 1532
if/interfaces/interface/enabled = 0
**dell-if/if/interfaces/interface/tagged-ports = e101-001-0**

Please let me know for any clarification

Thanks,
-Atanu

**Comment by james-jra** [comment]
Ah, so you don't need to create a VLAN subinterface before assigning it as a tagged port - it's explicitly created when you add the interface as a tagged port on the VLAN.
We just don't have control of the VLAN subinterface itself via CPS, but will at some future point.

I understand, that's very helpful,

thank you.
James

**Comment by atanu-mandal** [comment]
Sure James. Thanks. I am going to close this issue.
