### ISSUE TITLE
'Key Error: 0' in cps_utils.printable()

### ISSUE THREAD

**Issue by dimbleby** [open-switch/opx-cps#51]
I create a new interface via CPS, and call `cps_utils.printable()` on the changes reported back to me, something like this:

```python
    cps.transaction(obj):
    changes = [t['change'] for t in obj]
    for change in changes:
        cps_utils.printable(change)
```

But I get this error:

```
Traceback (most recent call last):
  File "/opt/metaswitch/pymm/pymm_cps_common.py", line 82, in write
    cps_utils.printable(change)
  File "/usr/lib/opx/cps_utils.py", line 315, in printable
    cps_attr_types_map.printable(obj)
  File "/usr/lib/opx/cps_utils.py", line 213, in printable
    self.printable_dict(data)
  File "/usr/lib/opx/cps_utils.py", line 207, in printable_dict
    data[k] = str(self.from_data(k, data[k]))
  File "/usr/lib/opx/cps_utils.py", line 148, in from_data
    return bytearray_utils.ba_to_value(t, val)
  File "/usr/lib/opx/bytearray_utils.py", line 259, in ba_to_value
    return ba_to_type[typ](typ, val)
  File "/usr/lib/opx/bytearray_utils.py", line 220, in ba_to_int_type
    return from_ba(val, t)
  File "/usr/lib/opx/bytearray_utils.py", line 98, in from_ba
    s = struct.unpack(pack_type_map_from_len[length], ba[0:length])[0]
KeyError: 0
```

Logging show that the content of `changes` is as follows - I don't know which is the problematic value:

```
2018-01-31 13:06:49,005 UTC INFO changes [{'operation': 'action', 'data': {'base-if-phy/if/interfaces/interface/npu-id': bytearray(b'\x00\x00\x00\x00'), 'dell-if/if/interfaces/interface/duplex': bytearray(b'\x03\x00\x00\x00'), 'dell-if/if/interfaces/interface/phys-address': bytearray(b'08:00:27:c8:2a:3f\x00'), 'base-if-phy/hardware-port/front-panel-port': bytearray(b'\x17\x00\x00\x00'), 'if/interfaces/interface/name': bytearray(b'e101-023-0\x00'), 'dell-base-if-cmn/if/interfaces/interface/if-index': bytearray(b'*\x00\x00\x00'), 'dell-base-if-cmn/set-interface/input/operation': bytearray(b'\x01\x00\x00\x00'), 'if/interfaces/interface/type': bytearray(b'ianaift:ethernetCsmacd\x00'), 'cps/object-group/return-code': bytearray(b'\x00\x00\x00\x00'), 'base-if-phy/hardware-port/subport-id': bytearray(b'\x00\x00\x00\x00'), 'dell-if/if/interfaces/interface/speed': bytearray(b'\x08\x00\x00\x00'), 'base-if-phy/if/interfaces/interface/port-id': bytearray(b'q\x00\x00\x00'), 'base-if-phy/if/interfaces/interface/phy-media': bytearray(b''), 'if/interfaces/interface/enabled': bytearray(b'\x01\x00\x00\x00'), 'base-if-phy/if/interfaces/interface/supported-autoneg': bytearray(b'\x04\x00\x00\x00'), 'dell-if/if/interfaces/interface/negotiation': bytearray(b'\x01\x00\x00\x00')}, 'key': '1.19.1245192.'}]
```

We did not see this failure on the OPX 2.1 VM, but are seeing it on the 2.2 VM.

**Comment by dimbleby** [comment]
I did a little debugging - the problematic value seems to be the empty string:

```
'base-if-phy/if/interfaces/interface/phy-media': bytearray(b'')
```

which, presumably, should be converted into ... an empty string?

**Comment by atanu-mandal** [comment]
Can you please elaborate bit more what you are trying ...from VM (running 2.2.0.0-dev2) it works if I run below 
root@OPX:~# cps_get_oid.py target/base-if-phy/physical

============1.17.1114163.1114115.1114116.==========
base-if-phy/physical/phy-mode = 1
base-if-phy/physical/npu-id = 0
base-if-phy/physical/hardware-port-list = 1,2,3,4
base-if-phy/physical/hardware-port-id = 1
base-if-phy/physical/speed = 6
base-if-phy/physical/port-id = 1
base-if-phy/physical/front-panel-number = 7
base-if-phy/physical/loopback = 0
------------------------------------------------
base-if-phy/physical/phy-mode = 1
base-if-phy/physical/npu-id = 0
base-if-phy/physical/hardware-port-list = 5,6,7,8
base-if-phy/physical/hardware-port-id = 5
base-if-phy/physical/speed = 6
base-if-phy/physical/port-id = 5
base-if-phy/physical/front-panel-number = 8
base-if-phy/physical/loopback = 0
------------------------------------------------
 Is the same working on hardware ?

**Comment by dimbleby** [comment]
We are writing our own applications using your python APIs.  In this case I deleted and then re-created an interface (e101-020-0, say) - and on creation the 'changes' were per my initial report.

From there it's very easy to reproduce the bug:

```python
changes = [{'operation': 'action', 'data': {'base-if-phy/if/interfaces/interface/npu-id': bytearray(b'\x00\x00\x00\x00'), 'dell-if/if/interfaces/interface/duplex': bytearray(b'\x03\x00\x00\x00'), 'dell-if/if/interfaces/interface/phys-address': bytearray(b'08:00:27:c8:2a:3f\x00'), 'base-if-phy/hardware-port/front-panel-port': bytearray(b'\x17\x00\x00\x00'), 'if/interfaces/interface/name': bytearray(b'e101-023-0\x00'), 'dell-base-if-cmn/if/interfaces/interface/if-index': bytearray(b'*\x00\x00\x00'), 'dell-base-if-cmn/set-interface/input/operation': bytearray(b'\x01\x00\x00\x00'), 'if/interfaces/interface/type': bytearray(b'ianaift:ethernetCsmacd\x00'), 'cps/object-group/return-code': bytearray(b'\x00\x00\x00\x00'), 'base-if-phy/hardware-port/subport-id': bytearray(b'\x00\x00\x00\x00'), 'dell-if/if/interfaces/interface/speed': bytearray(b'\x08\x00\x00\x00'), 'base-if-phy/if/interfaces/interface/port-id': bytearray(b'q\x00\x00\x00'), 'base-if-phy/if/interfaces/interface/phy-media': bytearray(b''), 'if/interfaces/interface/enabled': bytearray(b'\x01\x00\x00\x00'), 'base-if-phy/if/interfaces/interface/supported-autoneg': bytearray(b'\x04\x00\x00\x00'), 'dell-if/if/interfaces/interface/negotiation': bytearray(b'\x01\x00\x00\x00')}, 'key': '1.19.1245192.'}]
for change in changes:
    cps_utils.printable(change)
```

**Comment by atanu-mandal** [comment]
I have tried deleting and recreating the interface (i.e. e101-002-0) and everything seems to be working fine. Please refer the log below. I have executed this on a VM running 2.2.0-dev2. You may want to double check if anything is missing in your application.

root@OPX:~# **ifconfig e101-002-0**
e101-002-0 Link encap:Ethernet  HWaddr 00:50:56:94:53:3e
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)


**Delete Port:**
--------------
root@OPX:~# **cps_set_oid.py -qua target -oper action dell-base-if-cmn/set-interface dell-base-if-cmn/set-interface/input/operation=2 if/interfaces/interface/name=e101-002-0**
Success
Key: 1.19.1245192.
cps/object-group/return-code = 0
dell-base-if-cmn/set-interface/input/operation = 2
if/interfaces/interface/name = e101-002-0


root@OPX:~# **ifconfig e101-002-0**
e101-002-0: error fetching interface information: Device not found

**Recreate the port**
-------------------
root@OPX:~# **cps_set_oid.py -qua target -oper action dell-base-if-cmn/set-interface dell-base-if-cmn/set-interface/input/operation=1 if/interfaces/interface/name=e101-002-0 if/interfaces/interface/type=ianaift:ethernetCsmacd**
Success
Key: 1.19.1245192.
dell-base-if-cmn/if/interfaces/interface/if-index = 39
if/interfaces/interface/name = e101-002-0
if/interfaces/interface/type = ianaift:ethernetCsmacd
cps/object-group/return-code = 0
dell-base-if-cmn/set-interface/input/operation = 1
dell-if/if/interfaces/interface/negotiation = 1


root@OPX:~# **ifconfig e101-002-0**
e101-002-0 Link encap:Ethernet  HWaddr b2:81:d8:03:ba:04
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

root@OPX:~# **cps_get_oid.py target/base-if-phy/physical**

============1.17.1114163.1114115.1114116.==========
base-if-phy/physical/phy-mode = 1
base-if-phy/physical/npu-id = 0
base-if-phy/physical/hardware-port-list = 1,2,3,4
base-if-phy/physical/hardware-port-id = 1
base-if-phy/physical/speed = 6
base-if-phy/physical/port-id = 1
base-if-phy/physical/front-panel-number = 7
base-if-phy/physical/loopback = 0

root@OPX:~# **cps_get_oid.py target/base-if-phy/front-panel-port** 

============1.17.1114161.1114132.==========
base-if-phy/front-panel-port/default-name = e101-001-0
base-if-phy/front-panel-port/default-breakout-mode = 4
base-if-phy/front-panel-port/default-port-speed = 6
base-if-phy/front-panel-port/media-id = 1
base-if-phy/front-panel-port/port = 25,26,27,28
base-if-phy/front-panel-port/default-phy-mode = 1
base-if-phy/front-panel-port/breakout-mode = 4
base-if-phy/front-panel-port/port-speed = 6
base-if-phy/front-panel-port/br-cap/port-speed = 4
base-if-phy/front-panel-port/br-cap/skip-ports = 0
base-if-phy/front-panel-port/br-cap/phy-mode = 1
base-if-phy/front-panel-port/br-cap/breakout-mode = 2
base-if-phy/front-panel-port/br-cap/port-speed = 6
base-if-phy/front-panel-port/br-cap/skip-ports = 3
base-if-phy/front-panel-port/br-cap/phy-mode = 1
base-if-phy/front-panel-port/br-cap/breakout-mode = 4
base-if-phy/front-panel-port/mac-offset = 1
base-if-phy/front-panel-port/front-panel-port = 1
base-if-phy/front-panel-port/control-port = 25
base-if-phy/front-panel-port/npu-id = 0

**Comment by dimbleby** [comment]
Hi, 

I am not sure what is different on your system, but I certainly get the `'change'` response per my bug report!

Did you try executing the code fragment in my previous comment?  Do we agree that if CPS does return the object that I saw it return, then `cps_utils.printable()` will fall over?

Either way, I do not expect that this should be difficult to fix...  Somewhere in `cps_utils.printable()`, you just want a case that recognises an empty byte array and converts it into an empty string - right?  Is there any downside in making this change?

Cheers

David

**Comment by dimbleby** [comment]
PS when I run the exact commands that you suggest on a fresh OPX2.2 VM I see that they succeeds the first time, but that on a subsequent attempt the transaction fails.

Would you like a new issue for this?

**Comment by atanu-mandal** [comment]
If there is an issue with utility function e.g. cps_utils.printable() we would definitely fix that, but  I guess that is not blocking for your application, please check cps_utils.print_obj() and use of this in different repos. Hope that would suffice your requirement. 

For other failure, go ahead and open a new issue.

**Comment by dimbleby** [comment]
> If there is an issue with utility function e.g. cps_utils.printable() we would definitely fix that

Super!  That's exactly what this issue covers.  I'm not sure how this was unclear, but my apologies if it was so.

>  please check cps_utils.print_obj()

I am afraid this does not help.   We don't actually want to print the object, we simply want to convert it into a sensible data structure so as to update our own internal state.  (If there's a better way to do that than `cps_utils.printable()`, we'd be glad to hear about it).

> For other failure, go ahead and open a new issue.

No problem - this is now #53

**Comment by atanu-mandal** [comment]
Please incorporate the following changes in /usr/lib/opx/cps_utils.py on the target. This should resolve the issue with cps_utils.printable(). Note this would have "None" in case of empty bitearray.

With below change the output should look similar
==
{'operation': 'action', 'data': {'base-if-phy/if/interfaces/interface/npu-id': '0', 'dell-if/if/interfaces/interface/duplex': '3', 'dell-if/if/interfaces/interface/phys-address': '08:00:27:c8:2a:3f', 'if/interfaces/interface/type': 'ianaift:ethernetCsmacd', 'if/interfaces/interface/name': 'e101-023-0', 'dell-base-if-cmn/if/interfaces/interface/if-index': '42', 'base-if-phy/if/interfaces/interface/phy-media': None, 'base-if-phy/hardware-port/front-panel-port': '23', 'cps/object-group/return-code': '0', 'base-if-phy/hardware-port/subport-id': '0', 'dell-if/if/interfaces/interface/speed': '8', 'base-if-phy/if/interfaces/interface/port-id': '113', 'dell-base-if-cmn/set-interface/input/operation': '1', 'if/interfaces/interface/enabled': '1', 'base-if-phy/if/interfaces/interface/supported-autoneg': '4', 'dell-if/if/interfaces/interface/negotiation': '1'}, 'key': '1.19.1245192.'}
==

opx-cps/scripts/lib/cps_utils.py

git diff
diff --git a/scripts/lib/cps_utils.py b/scripts/lib/cps_utils.py
index 731dbe8..c6bbd25 100644
--- a/scripts/lib/cps_utils.py
+++ b/scripts/lib/cps_utils.py
@@ -204,7 +204,8 @@ class CPSTypes:
             elif isinstance(data[k], dict):
                 self.printable_dict(data[k])
             else:
-                data[k] = str(self.from_data(k, data[k]))
+                if len(data[k]) == 0: data[k] = None
+                else: data[k] = str(self.from_data(k, data[k]))

     def printable(self,obj):
         data = obj['data']

=====

Hope this helps.
We will send the changes for code review.

**Comment by atanu-mandal** [comment]
https://review.openswitch.net/#/c/14531/

**Comment by atanu-mandal** [comment]
Closing this issue as the fix is merged.
