### ISSUE TITLE
Content of vlan interfaces state

### ISSUE THREAD

**Issue by james-jra** [open-switch/opx-cps#52]
I'm attempting to get state information for VLAN interfaces.
The following fields from dell-if-vlan.yang are absent when querying `dell-base-if-cmn/if/interfaces-state/interface`:
* `dell-if/if/interfaces/interface/untagged-ports`
* `dell-if/if/interfaces/interface/tagged-ports`
* `base-if-vlan/if/interfaces/interface/id`
* `dell-if/if/interfaces/interface/vlan-type`

It would certainly be useful to be able to query the state of these absent fields via `dell-base-if-cmn/if/interfaces-state/interface`.
I also understand a similar situation is true for LAG interfaces (id, unblock-port-list, block-port-list)

I realise the fields I've listed here actually belong to `dell-base-if-cmn/if/interfaces/interface` (not interfaces-state). However there is precedent for exposing useful equivalent interfaces fields in `dell-base-if-cmn/if/interfaces-state/interface`, for example we get the following fields from `if/interfaces-state`, even though the YANG model defines them under `if/interfaces`: 
* `dell-if/if/interfaces/interface/phys-address`
* `dell-if/if/interfaces/interface/mtu`
* `if/interfaces/interface/enabled`

Do you intend to support accessing these fields for VLAN and LAG interfaces through the above query?

If not, how should I determine which fields are actually accessible through interfaces-state, if the YANG models alone do not indicate it?

**Comment by peterbrittain** [comment]
As per our call yesterday, here's a quick summary of where we're currently looking for data across various interface types.

```
# Data we currently get from state even though it is not present in the state yang model
dell-if/if/interfaces/interface/phys-address
dell-if/if/interfaces/interface/mtu
if/interfaces/interface/enabled

# Data we currently get from config because it's not in state 
base-if-lag/if/interfaces/interface/id
base-if-lag/if/interfaces/interface/lag-opaque-data
base-if-lag/if/interfaces/interface/unblock-port-list
base-if-lag/if/interfaces/interface/block-port-list

base-if-vlan/if/interfaces/interface/id
dell-if/if/interfaces/interface/untagged-ports
dell-if/if/interfaces/interface/tagged-ports
dell-if/if/interfaces/interface/vlan-type
dell-if/if/interfaces/interface/learning-mode
```

If you could confirm which model you plan to use (duplicating key data in state, or having a clear split of config and state with no duplication) and fix up any inconsistencies, we can code to either approach.

**Comment by atanu-mandal** [comment]
For VLAN interface now the information is provided as below. 

cps_get_oid.py -qua target dell-base-if-cmn/if/interfaces/interface if/interfaces/interface/type=ianaift:l2vlan if/interfaces/interface/name=br201

============dell-base-if-cmn/if/interfaces/interface==========

dell-base-if-cmn/if/interfaces/interface/if-index = 43
dell-if/if/interfaces/interface/phys-address = 00:50:56:94:02:8b
if/interfaces/interface/type = ianaift:l2vlan
dell-if/if/interfaces/interface/untagged-ports = e101-007-0,e101-006-0
base-if-vlan/if/interfaces/interface/id = 201
if/interfaces/interface/name = br201
dell-if/if/interfaces/interface/vlan-type = 1
dell-if/if/interfaces/interface/learning-mode = 1
dell-if/if/interfaces/interface/mtu = 1532
if/interfaces/interface/enabled = 0
dell-if/if/interfaces/interface/tagged-ports = e101-009-0,e101-008-0

**Comment by atanu-mandal** [comment]
"interfaces-state" is not provided for VLAN interface. Now all the information required for VLAN is available through "interfaces" model as mentioned above. Hope that would suffice the ask.

**Comment by atanu-mandal** [comment]
We are working on to provide interface-state for VLAN as well.

**Comment by jeff-yin** [comment]
Will be fixed in 3.0.0 along with #48

**Comment by GarrickHe** [comment]
Update - UT completed. Fix is in code-review.

**Comment by jeff-yin** [comment]
Fixed by https://github.com/open-switch/opx-nas-interface/pull/34
