### ISSUE TITLE
Intended use of negotiation/auto-negotiation

### ISSUE THREAD

**Issue by james-jra** [open-switch/opx-cps#54]
I'm writing application logic to allow a user to configure auto-negotiation on an interface.
I am confused about the usage of the two following fields (from [dell-interface.yang](https://github.com/open-switch/opx-base-model/blob/master/yang-models/dell-interface.yang)):
*  `dell-if/if/interfaces/interface/auto-negotiation`
* `dell-if/if/interfaces/interface/negotiation`

**Questions**
What's the difference between `negotiation` and `auto-negotiation`?
Why does opx-ethtool configure `negotiation` to auto/on/off instead of directly setting `auto-negotiation`?
If I should configure `negotiation`, this should be included when querying interface configuration using CPS.

**Context**
I have looked at the opx-ethtool script.
It uses `auto-negotiation` for *showing* interface configuration, but `negotiation` for *setting* interface configuration.

Testing on my OPX 2.2 VM shows the following behaviour:
* Setting `negotiation = on` causes `auto-negotiation = 1`
* Setting `negotiation = auto or off` causes `auto-negotiation = 0`
* The information in  `cps-get-oid.py dell-base-if-cmn/if/interfaces/interface` includes `auto-negotiation`, but not `negotiation`:

```
root@OPX:~# sudo cps_get_oid.py dell-base-if-cmn/if/interfaces/interface if/interfaces/interface/name=e101-021-0                                                                                                               
============1.19.44.2883617.2883612.2883613.==========
base-if-phy/if/interfaces/interface/npu-id = 0
dell-base-if-cmn/if/interfaces/interface/if-index = 9
dell-if/if/interfaces/interface/phys-address = 34:17:eb:2c:d7:51
dell-if/if/interfaces/interface/speed = 0
base-if-phy/if/interfaces/interface/learn-mode = 3
if/interfaces/interface/name = e101-021-0
dell-if/if/interfaces/interface/duplex = 1
dell-if/if/interfaces/interface/auto-negotiation = 0
if/interfaces/interface/type = ianaift:ethernetCsmacd
dell-if/if/interfaces/interface/fec = 3
dell-if/if/interfaces/interface/mode = 1
base-if-phy/if/interfaces/interface/port-id = 21
dell-if/if/interfaces-state/interface/supported-speed = 3,4,5,6,10,7
dell-if/if/interfaces/interface/mtu = 1532
base-if-phy/if/interfaces/interface/phy-media = 1
if/interfaces/interface/enabled = 1
base-if-phy/if/interfaces/interface/tagging-mode = 3
```

**Comment by atanu-mandal** [comment]
When auto-negotiation gets enabled the interface auto negotiates both speed and duplex. In other cases speed/duplex/speed & duplex are fixed. Please let me know if it clarifies.

**Comment by james-jra** [comment]
I've looked at this in more detail. I believe the behaviour described above is incorrect.
I think the behaviour is:
* set `negotiation = on` -> `auto-negotiation = 1`
* set `negotiation = off` -> `auto-negotiation = 0`
* set `negotiation = auto` -> no change to `auto-negotiation`

So I plan to directly set `dell-if/if/interfaces/interface/auto-negotiation` instead of using `dell-if/if/interfaces/interface/negotiation`.

**Comment by atanu-mandal** [comment]
Auto Negotiation setting depends on the capability of physical media connected to the interface. For example, we should enable auto-neg by default for CR4 (copper) media and disable auto-neg for SR4 (fiber). 
Now in case of "negotiation = auto", depending on the media connected NAS module sets the auto-negotiation. 
If user sets something other than AUTO(i.e. default) the configuration will be passed down without checking connected media.
That's why we may see the auto-negotiation value gets updated depending on the physical media type when "negotiation = on"

**Comment by atanu-mandal** [comment]
For reference :

https://github.com/open-switch/opx-platform-config/blob/master/vendor/dell/s6000/etc/opx/phy_media_default_npu_setting.xml

https://github.com/open-switch/opx-nas-interface/blob/master/scripts/bin/base_nas_front_panel_ports.py

**Comment by atanu-mandal** [comment]
This should work as follows..

negotiation = on, auto-negotiation is set as 1
negotiation = off,  auto-negotiation is set as 0 (set the speed/duplex as required)
negotiation = auto, auto-negotiation gets updated based on the physical media’s capability.

**Comment by atanu-mandal** [comment]
Great, thanks.

I am going to close this.
