### ISSUE TITLE
Configuring an interface's duplex mode to "Auto" actually sets it to "Full".

### ISSUE THREAD

**Issue by james-jra** [open-switch/opx-cps#55]
In CPS you expose 3 options for interface duplex mode:
* Full
* Half
* Auto

Configuration works as expected for Full and Half, but not for Auto.
Setting duplex = Auto actually results in duplex = Full.

**Trace:**
```
# Before
opxUser@opx_vm:~$ sudo cps_get_oid.py dell-base-if-cmn/if/interfaces/interface if/interfaces/interface/name=e101-021-0 | grep duplex

dell-if/if/interfaces/interface/duplex = 2   # "Half"

# Successfully set to Auto - even returns changed value!
opxUser@opx_vm:~$ sudo cps_set_oid.py -qua target -oper action dell-base-if-cmn/set-interface dell-base-if-cmn/set-interface/input/operation=3 if/interfaces/interface/name=e101-021-0 dell-if/if/interfaces/interface/duplex=3

Success
Key: 1.19.1245192.
dell-if/if/interfaces/interface/duplex = 3    # "Auto"
dell-base-if-cmn/set-interface/input/operation = 3
if/interfaces/interface/name = e101-021-0
cps/object-group/return-code = 0

# After - duplex = full (1) not auto (3)
opxUser@opx_vm:~$ sudo cps_get_oid.py dell-base-if-cmn/if/interfaces/interface if/interfaces/interface/name=e101-021-0 | grep duplex

dell-if/if/interfaces/interface/duplex = 1  # "Full"
```

**Cause:**
See https://github.com/open-switch/opx-nas-ndi/blob/master/src/nas_ndi_port.c#L1016 

Basically, NAS does not honour the Auto option. It always sets duplex = Full instead of Auto.
This means after setting duplex to Auto, subsequent queries still return Full, causing the inconsistency described above.

**Comment by atanu-mandal** [comment]
You are right. We will check if/how we can handle this. As you had mentioned the code says TBD
/* TODO in case of AUTO set it to FULL: TBD */

**Comment by atanu-mandal** [comment]
Hi James, it also depends on whether SAI has support of Auto mode.
    sai_attr.value.booldata = (duplex == BASE_CMN_DUPLEX_TYPE_HALF) ? false : true;
    sai_attr.id = SAI_PORT_ATTR_FULL_DUPLEX_MODE; 

SAI_PORT_ATTR_FULL_DUPLEX_MODE type is boolean (for AUTO it sets as FULL DUPLEX).

Does it clarify a bit? Thanks.

**Comment by james-jra** [comment]
I think we are in agreement:
* SAI ports have a boolean attribute (SAI_PORT_ATTR_FULL_DUPLEX_MODE)
* Configuring "duplex" in CPS executes the `ndi_port_duplex_set` function in NAS (shown below)
* In this function:
    * If duplex is **half**, set SAI_PORT_ATTR_FULL_DUPLEX_MODE = 0
    * If duplex is **full**, set SAI_PORT_ATTR_FULL_DUPLEX_MODE = 1
    * If duplex is **auto**, set SAI_PORT_ATTR_FULL_DUPLEX_MODE = 1

For the purposes of my application, I can just set "full" or "half" and ignore "auto"

However it is confusing if CPS allows the user to configure "auto", the transaction appears successful, and then when the user queries the configuration, it shows "full" (as in the trace in the original post).

```
t_std_error ndi_port_duplex_set(npu_id_t npu_id, npu_port_t port_id,
        BASE_CMN_DUPLEX_TYPE_t duplex) {

    sai_attribute_t sai_attr;
   /* TODO in case of AUTO set it to FULL: TBD */
    sai_attr.value.booldata = (duplex == BASE_CMN_DUPLEX_TYPE_HALF) ? false : true;
    sai_attr.id = SAI_PORT_ATTR_FULL_DUPLEX_MODE;

    return _sai_port_attr_set_or_get(npu_id,port_id,SAI_SG_ACT_SET,&sai_attr,1);
}
```

**Comment by atanu-mandal** [comment]
Hi James, sure we are in full agreement to understand the current behavior. Your approach looks fine.

**Comment by atanu-mandal** [comment]
Closing this issue.
