### ISSUE TITLE
Can't perform "set" operation on ACL object

### ISSUE THREAD

**Issue by mcallisterjp** [open-switch/opx-cps#56]
ACLs in the `base-acl/table` YANG list don't seem to be configurable after they have been created:
```
opxUser@opx_vm:~$ sudo cps_get_oid.py target base-acl/table id=4

Key: 1.47.3080336.3080284.
base-acl/table/npu-id-list = 0
base-acl/table/id = 4
base-acl/table/stage = 1
base-acl/table/priority = 0
base-acl/table/allowed-match-fields = 1,2,5,6
base-acl/table/size = 0
opxUser@opx_vm:~$ sudo cps_set_oid.py set base-acl/table id=4 priority=1
opxUser@opx_vm:~$ echo $?
0
opxUser@opx_vm:~$ sudo cps_get_oid.py target base-acl/table id=4

Key: 1.47.3080336.3080284.
base-acl/table/npu-id-list = 0
base-acl/table/id = 4
base-acl/table/stage = 1
base-acl/table/priority = 0
base-acl/table/allowed-match-fields = 1,2,5,6
base-acl/table/size = 0
opxUser@opx_vm:~$ sudo cps_set_oid.py set base-acl/table id=4 name=test 
opxUser@opx_vm:~$ echo $?
0
opxUser@opx_vm:~$ sudo cps_get_oid.py target base-acl/table id=4

Key: 1.47.3080336.3080284.
base-acl/table/npu-id-list = 0
base-acl/table/id = 4
base-acl/table/stage = 1
base-acl/table/priority = 0
base-acl/table/allowed-match-fields = 1,2,5,6
base-acl/table/size = 0
```

I have noticed the same behaviour using the CPS python API, with the syslog message: `Feb  7 14:44:17 opx_vm opx_nas_daemon[585]: [ACL:NAS-ACL], Operation 3 NOT allowed on Obj`. Is this intended behaviour? If so, is it documented anywhere? Do configuration operations have to be two-stage create/delete operations?

This is on the v2.2 VM.

**Comment by atanu-mandal** [comment]
"Set" operation is only applicable for "base-acl/entry" (this supports Create/Delete/Set), all other entities i.e. table, range,counter would have Create/Delete support. 
So the log message looks to be legitimate here.
We would document this.

**Comment by mcallisterjp** [comment]
Thanks Atanu. Are there plans to allow set operations on `base-acl/table` in future?

**Comment by atanu-mandal** [comment]
Hi Pete, not yet. We will update for any such plan.
