### ISSUE TITLE
Problem with ACL names

### ISSUE THREAD

**Issue by mcallisterjp** [open-switch/opx-cps#57]
Configuring a name on an ACL object (the `base-acl/table/name` leaf) appears not to work:
```
opxUser@opx_vm:~$ sudo cps_set_oid.py create base-acl/table id=7 name="test" stage=1 allowed-match-fields=1 priority=7
Success
Key: 1.47.3080336.3080284.
base-acl/table/id = 7
cps/object-group/return-code = 0
base-acl/table/id = 7
0 = test
base-acl/table/stage = 1
base-acl/table/priority = 7
base-acl/table/allowed-match-fields = 1
opxUser@opx_vm:~$ sudo cps_get_oid.py target base-acl/table id=7

Key: 1.47.3080336.3080284.
base-acl/table/npu-id-list = 0
base-acl/table/id = 7
base-acl/table/stage = 1
base-acl/table/priority = 7
base-acl/table/allowed-match-fields = 1
base-acl/table/size = 0
```

Presumably the `0 = test` line in the create output is relevant for understanding why!

Can also reproduce with CPS python API.

**Comment by atanu-mandal** [comment]
Looks like you are using older version of OPX (e.g. 2.1.0) installer. With latest 2.2.0 this should be working fine. Please refer the output below.

root@OPX:~# cps_set_oid.py -oper create base-acl/table id=7 name="test" stage=1 allowed-match-fields=1 priority=7
Success
Key: 1.47.3080336.3080284.
base-acl/table/id = 7
base-acl/table/id = 7
cps/object-group/return-code = 0
base-acl/table/stage = 1
base-acl/table/priority = 7
base-acl/table/allowed-match-fields = 1
base-acl/table/name = test                        =====> Expected value

root@OPX:~# cps_get_oid.py base-acl/table id=7

============1.47.3080336.3080284.==========
base-acl/table/npu-id-list = 0
base-acl/table/id = 7
base-acl/table/stage = 1
base-acl/table/priority = 7
base-acl/table/allowed-match-fields = 1
base-acl/table/name = test                       =====> Expected value
base-acl/table/size = 0

**Comment by mcallisterjp** [comment]
Thanks Atanu. I am running some kind of 2.2 VM, but it might well be an early dev-candidate rather than the final version. I will try upgrading and retest.

**Comment by mcallisterjp** [comment]
FYI, I thought I was running the 2.2 VM in the first place because I got the installer from https://archive.openswitch.net/vm-tools/2.2.0/lvm as suggested by https://github.com/open-switch/opx-docs/wiki/Run-virtual-machine.

Despite the URL, it installed VM 2.1. Who should I raise this problem with? An issue on the opx-docs project?

**Comment by atanu-mandal** [comment]
Yes, please go ahead. I am closing the current one.
