### ISSUE TITLE
configured speed only shown when interface is oper-up

### ISSUE THREAD

**Issue by james-jra** [open-switch/opx-cps#59]
When I configure the speed of an interface (`dell-if/if/interfaces/interface/speed`), the transaction succeeds and returns the changed value.
But when I then query the target configuration, it always returns 0 unless the interface is oper-up.

If I successfully apply configuration, I should be able to view that configuration (and confirm it is correct).

Note, I've found the code which performs this query: https://github.com/open-switch/opx-nas-ndi/blob/master/src/nas_ndi_port.c#L700 
The codepath for getting `dell-if/if/interfaces/interface/speed` is hardcoded to call the above function with `check_link = True`, therefore it always returns `0` when the interface is oper-down.

Also, I considered maybe the `speed` field is intended to show the *negotiated* speed for the interface when it is oper-up?
If this is true, then I would expect there to be a separate field used to set the *desired* speed of the interface.

So: 
* What is the intended use of the `dell-if/if/interfaces/interface/speed` field?
* If I set this field to a value (seting the desired speed of the interface), how can I reliably view that configuration?

**Trace:**
```
# Setting speed succeeds
root@OPX1:~# cps_set_oid.py -qua target -oper action dell-base-if-cmn/set-interface dell-base-if-cmn/set-interface/input/operation=3 if/interfaces/interface/name=e101-001-4 dell-if/if/interfaces/interface/speed=3
Success
Key: 1.19.1245192.
cps/object-group/return-code = 0
dell-if/if/interfaces/interface/speed = 3
dell-base-if-cmn/set-interface/input/operation = 3
if/interfaces/interface/name = e101-001-4

# But speed is still 0
root@OPX1:~# sudo cps_get_oid.py dell-base-if-cmn/if/interfaces/interface if/interfaces/interface/name=e101-001-4

Key: 1.19.44.2883617.2883612.2883613.
base-if-phy/if/interfaces/interface/npu-id = 0
dell-base-if-cmn/if/interfaces/interface/if-index = 40
dell-if/if/interfaces/interface/phys-address = ec:f4:bb:fd:53:80
dell-if/if/interfaces/interface/speed = 0
base-if-phy/if/interfaces/interface/learn-mode = 3
if/interfaces/interface/name = e101-001-4
dell-if/if/interfaces/interface/duplex = 1
dell-if/if/interfaces/interface/auto-negotiation = 0
if/interfaces/interface/type = ianaift:ethernetCsmacd
base-if-phy/if/interfaces/interface/port-id = 28
dell-if/if/interfaces-state/interface/supported-speed = 2,3,4
dell-if/if/interfaces/interface/mtu = 1532
if/interfaces/interface/enabled = 1


# Now oper-up, we see the correct speed
root@OPX1:~# opx-ethtool e101-001-4
Settings for e101-001-4:
    Media Type: QSFP 40GBASE CR4
    Part Number: 616760003
    Serial Number: CN027GG574F8JUC
    Qualified: Yes
    Administrative State: UP
    Operational State: UP
    Supported Speed (in Mbps):  [100, 1000, 10000]
    Auto Negotiation : off
    Speed   : 10000
    Duplex   : full
```

**Comment by atanu-mandal** [comment]
This is being worked on to provide the option to retrieve the desired speed for an interface.

**Comment by GarrickHe** [comment]
I have a fix. It is currently in code-review.

**Comment by atanu-mandal** [comment]
https://review.openswitch.net/#/c/14572/

**Comment by atanu-mandal** [comment]
The fix is merged.

**Comment by atanu-mandal** [comment]
Closing this. Please reopen for any further issue.
