### ISSUE TITLE
Can't configure LAG blocked/unblocked ports at once

### ISSUE THREAD

**Issue by james-jra** [open-switch/opx-cps#61]
When I try to configure a LAG Interface object in CPS with `blocked-ports` and `unblocked-ports`, all of the ports I included in **both** lists end up in `blocked-ports`.

I've worked around this by doing two separate transactions - one to set `blocked-ports`, a second for `unblocked-ports`.

However, this is still inconsistent with how CPS treats lists of ports.
For example, when configuring VLAN interfaces, CPS will happily configure `tagged-ports` and `untagged-ports` in a single transaction. LAG interfaces should act in the same way.

**Trace:**
```
# Create a lag port
opxUser@opx_vm:~$ sudo cps_config_lag.py --create --lname bnd2
Success

# Give it some member ports
opxUser@opx_vm:~$ sudo cps_config_lag.py --add --lname bnd2 --port e101-021-0,e101-022-0
Success

# So now I have an interface with some member ports (they go into unblocked by default)
opxUser@opx_vm:~$ sudo cps_get_oid.py dell-base-if-cmn/if/interfaces/interface if/interfaces/interface/name=bnd2 | grep port
dell-if/if/interfaces/interface/member-ports/name = e101-021-0
dell-if/if/interfaces/interface/member-ports/name = e101-022-0
base-if-lag/if/interfaces/interface/unblock-port-list = e101-022-0,e101-021-0
base-if-lag/if/interfaces/interface/block-port-list =

# Setting both blocked and unblocked ports seems to succeed
opxUser@opx_vm:~$ sudo cps_set_oid.py -qua target -oper action dell-base-if-cmn/set-interface dell-base-if-cmn/set-interface/input/operation=3 if/interfaces/interface/name=bnd2 if/interfaces/interface/type=ianaift:ieee8023adLag base-if-lag/if/interfaces/interface/block-port-list=e101-022-0 base-if-lag/if/interfaces/interface/unblock-port-list=e101-021-0
Success
Key: 1.19.1245192.
if/interfaces/interface/name = bnd2
if/interfaces/interface/type = ianaift:ieee8023adLag
cps/object-group/return-code = 0
base-if-lag/if/interfaces/interface/unblock-port-list = e101-021-0  <-----
dell-base-if-cmn/set-interface/input/operation = 3
base-if-lag/if/interfaces/interface/block-port-list = e101-022-0      <-----

# But in fact, all ports are found in the "blocked-ports" list
opxUser@opx_vm:~$ sudo cps_get_oid.py dell-base-if-cmn/if/interfaces/interface if/interfaces/interface/name=bnd2 | grep port
dell-if/if/interfaces/interface/member-ports/name = e101-021-0
dell-if/if/interfaces/interface/member-ports/name = e101-022-0
base-if-lag/if/interfaces/interface/unblock-port-list =
base-if-lag/if/interfaces/interface/block-port-list = e101-022-0,e101-021-0   <-------

```

**Comment by atanu-mandal** [comment]
Hi @james-jra, we will take care of this. With cps_config_lag utility it behaves fine.

root@OPX:~# cps_config_lag.py
<cps_config_lag:- Lag operations >
                 cps_config_lag.py  --create --lname <lagname>
                 cps_config_lag.py  --delete --lname <lagname>
                 cps_config_lag.py  --add --lname <lagname> --port <port_list>
                 cps_config_lag.py  --remove --lname <lagname> --port <port_list>
                 cps_config_lag.py  --set --lname <lagname> --port <block/unblock port_list> --frwd <yes/no>
                 cps_config_lag.py  --set --lname <lagname> --mac  <macaddr>
                 cps_config_lag.py  --set --lname <lagname> --admn <up/down>
                 cps_config_lag.py  --get --lname <lagname>
                 cps_config_lag.py  --lname <lagname> --mac-learn <drop/disable/hw/cpu_trap/cpu_log>

**Comment by james-jra** [comment]
Hi Atanu,
I understand the cps_config_lag utility behaves as expected.
That is because `cps_config_lag.py` does not allow the user to set both `blocked_ports` and `unblocked_ports` in a single operation - the user must do two separate operations.
This is the same thing I'm doing in my application to work around the problem.

E.g.
```
# set blocked ports
root@OPX:~# cps_config_lag.py --set --lname bnd2 --port e101-021-0,e101-022-0 --frwd no
# then set unblocked ports
root@OPX:~# cps_config_lag.py --set --lname bnd2 --port e101-023-0 --frwd yes
```

So this CPS issue is still relevant.
To be consistent with all other configuration fields, it should be possible to set both `blocked_ports` and `unblocked_ports` in a single transaction.

**Comment by atanu-mandal** [comment]
Hi James, I am just curious to understand the use case of setting both blocked-ports and unblocked-ports in a single operation. As we understand the unblock port gets added to the LAG when the operational state of the interface comes up which is dynamic in nature. It would be great if we can understand little bit more on the approach/use case to decide whether this functionality is required to implement. Thanks.

**Comment by james-jra** [comment]
I would expect that:
* The CPS YANG model defines the valid configuration that I can apply.
* I can apply any valid configuration in one transaction.
* Any limitations to valid configuration, or the ordering of operations is documented somewhere.

Use cases for configuring blocked/unblocked ports in one transaction:
* A user wants to unplug a cable, therefore must swap an active and backup port in the static LAG configuration. If they were using our application, they'd do something like "Configure lag 10, blocked ports e101-021-0, unblocked ports e101-022-0, commit".
* An application (e.g. an SDN controller) notices degraded performance on an active port, so it swaps an active and backup port in the static LAG configuration.

In either of the above use-cases, the user or application is trying to apply valid configuration. Therefore that transaction should succeed, and not require multiple transactions. If it did require multiple transactions, there would be a short time when the configuration has either both ports blocked, or both ports unblocked.

**Comment by atanu-mandal** [comment]
Hi @james-jra, thanks for your explanation. We would plan to enhance this feature after the upcoming release.

**Comment by GarrickHe** [comment]
I have a fix for this issue. Currently testing. Will update when it is pushed.

**Comment by GarrickHe** [comment]
@james-jra 
Issue fixed with this push:
https://review.openswitch.net/#/c/14763/

Thanks,
garrick
