### ISSUE TITLE
Need to provide a bogus interface type when retrieving interface statistics

### ISSUE THREAD

**Issue by dimbleby** [open-switch/opx-cps#62]
When retrieving interface statistics from `dell-base-if-cmn/if/interfaces-state/interface/statistics`, we need to provide not only the interface name but also an interface type. 

But what's really confusing: we sometimes need to provide an interface type that isn't the real interface type!

Eg:

```python
import cps
import cps_object
import cps_utils

data = {
    'if/interfaces-state/interface/name': 'lo',
    'if/interfaces-state/interface/type': 'ianaift:softwareLoopback',
}
obj = cps_object.CPSObject(
    qual='observed',
    module='dell-base-if-cmn/if/interfaces-state/interface/statistics',
    data=data,
)
response = []
if cps.get([obj.get()], response):
    for entry in response:
        cps_utils.print_obj(entry)
```

This returns just 10 statistics, omitting (among others) those relating to unicast packets.  

The same is true if I leave out the interface type from the query.

But the additional statistics are available.  To get at them it seems that I must provide the interface type `ianaift:ethernetCsmacd` (even though this really is a loopback interface).  Then I get lots more statistics, including the ones relating to unicast packets.

I would expect that:

* The API should not require an interface type at all when getting statistics.  (The name identifies the interface: surely CPS knows the interface type?)
* if the interface type really must be provided, then the correct type to provide should be the actual type of the interface

**Comment by atanu-mandal** [comment]
Essentially for software loopback interface  there is no such interface mapped (or created) at NPU level, this is basically a kernel only interface. So there is no statistics gathered from NDI layer , the data is captured from linux side. 
On related note when any ip address is configured to the loopback interface that gets programmed to NPU's route table. 
Currently interface type is only checked in statistics get function and accordingly the information is provided. We can have a check of both name and type before providing statistics.

**Comment by dimbleby** [comment]
Pete discussed this with you, and our current understanding is as follows:

* the right way to use the API to get statistics is: provide the interface name only (no need to provide a type)
* when we do this for the loopback interface, it is expected and correct that the set of statistics that is returned is smaller than for other interfaces
* when I provided type `ianaift:ethernetCsmacd` for the loopback interface, the extra statistics that I was seeing were in fact bogus!  
  * I should never have done this in the first place.

Is that all correct?  If so then that's fine, and we'll get the statistics without providing an interface type.

However if that is all correct, then you may want to fix the `opx-show-stats` utility - which always provides interface type `ianaift:ethernetCsmacd` when getting statistics.

**Comment by atanu-mandal** [comment]
Hi David, your understanding is correct. 
Yes, we would fix opx-show-stats utility , thanks for the catch! If you want please go ahead and create a new issue for that.

**Comment by dimbleby** [comment]
Thanks!

I don't care about opx-show-stats, please just track this internally.

David
