### ISSUE TITLE
No 'reject' packet action on ACL action fields

### ISSUE THREAD

**Issue by mcallisterjp** [open-switch/opx-cps#64]
The typedef `base-acl/packet-action-type` doesn't contain a 'reject' packet action, the semantics of which is to drop the packet and send an ICMP destination-unreachable message back to the source.

This is a common ACL action configurable in various other networking applications, including `iptables`. Are you planning to support it in CPS?

**Comment by atanu-mandal** [comment]
CPS supports various packet actions e.g. drop/forward/copy to cpu / trap to cpu and combinations among these attributes.
For above packet action I guess SAI does not provide such capability to send back new packet with dest-unreachable message. 
So this enhancement may be possible by using trap_to_cpu action to redirect packets to CPU and using some rule (e.g. iptables) in the kernel to realize reject actions. We do not have any such plan to support this yet but we should consider.

**Comment by jeff-yin** [comment]
This type of scenario is supported in OPX today. As another example, OPX will trap_to_cpu routed packets with TTL=1 in order to send back ICMP error messages. Closing for now unless @atanu-mandal or @mcallisterjp feel otherwise.
