### ISSUE TITLE
can't save L2 configuration with cps_set_oid.py

### ISSUE THREAD

**Issue by dj-s** [open-switch/opx-cps#78]
```cps_set_oid.py``` does not save L2 configuration.

## my setup

```
root@OPX:~# opx-show-version
OS_NAME="OPX"
OS_VERSION="2.2"
PLATFORM="S3048-ON"
ARCHITECTURE="x86_64"
INTERNAL_BUILD_ID="OpenSwitch blueprint for Dell 1.0.0"
BUILD_VERSION="2.2.0"
BUILD_DATE="2018-01-26T10:03:01-0800"
INSTALL_DATE="2018-02-20T23:16:15+0000"
SYSTEM_UPTIME= 2 minutes
SYSTEM_STATE= running
UPGRADED_PACKAGES=no
ALTERED_PACKAGES=no
```

## Reproduce

Create and apply a vlan on a UNTAGGED interface

```
root@OPX:/# cps_config_vlan.py --add --id 1011 --vlantype 1 --port e101-001-0,e101-002-0
Success
```

Now, verify the configuration with ```cps_get_oid.py```

```
root@OPX:/# cps_get_oid.py -qua target dell-base-if-cmn/if/interfaces/interface if/interfaces/interface/type=ianaift:l2vlan

============1.19.44.2883617.2883612.2883613.==========
dell-base-if-cmn/if/interfaces/interface/if-index = 56
dell-if/if/interfaces/interface/phys-address = 64:00:6a:aa:bb:cc
dell-if/if/interfaces/interface/untagged-ports = e101-002-0,e101-001-0
base-if-vlan/if/interfaces/interface/id = 1011
if/interfaces/interface/name = br1011
dell-if/if/interfaces/interface/vlan-type = 1
dell-if/if/interfaces/interface/learning-mode = 1
dell-if/if/interfaces/interface/mtu = 1532
if/interfaces/interface/enabled = 0
```

now, check the L2 connectivity with a device (here, my laptop)
```
root@OPX:/# opx-switch-shell "l2 show"
SAI.0>
```
in fact, it seems necessary to shut and no shut vlan and interfaces
```
root@OPX:/# ifconfig br1011 down
root@OPX:/# ifconfig e101-001-0 down
root@OPX:/# ifconfig e101-002-0 down
root@OPX:/# ifconfig br1011 up
root@OPX:/# ifconfig e101-001-0 up
root@OPX:/# ifconfig e101-002-0 up

root@OPX:/# opx-switch-shell "l2 show"
mac=00:22:20:aa:bb:cc vlan=1011 GPORT=0x1 modid=0 port=1/ge1 Hit
SAI.0>
```
Now, it seems ok (mac and untagged vlan)

For this test, set an ip address on br1011
```
root@OPX:/# ifconfig br1011 192.168.0.1 netmask 255.255.255.0
```
and ping your device
```
root@OPX:/# ping 192.168.0.2
PING 192.168.0.2 (192.168.0.2) 56(84) bytes of data.
64 bytes from 192.168.0.2: icmp_seq=1 ttl=128 time=0.490 ms
64 bytes from 192.168.0.2: icmp_seq=2 ttl=128 time=0.513 ms
64 bytes from 192.168.0.2: icmp_seq=3 ttl=128 time=0.518 ms
```
it's ok. you can check the result of  an ```arp -a``` command
```
root@OPX:/# arp -a
? (192.168.0.2) at 00:22:20:aa:bb:cc [ether] on br1011
```
all is fine, interfaces are configured with vlan 1011 (UNTAGGED) and ping is OK.

now, it's time to commit this "L2" configuration before a reboot.
```
root@OPX:/# cps_set_oid.py -oper set -db -qua target -commit-event dell-base-if-cmn/if/interfaces/interface switch-id=0
Success
Key: 1.19.44.2883617.2883612.2883613.
0 = 0
```
Now, reboot the switch and test the  `cps_get_oid` command
```
root@OPX:/# cps_get_oid.py -qua target dell-base-if-cmn/if/interfaces/interface if/interfaces/interface/type=ianaift:l2vlan
root@OPX:/#
```
nothing, all "L2" configuration is lost.

**Comment by GarrickHe** [comment]
@dj-s 
I'll take a look at this issue.

**Comment by madhu222** [comment]
@dj-s You can modify the /etc/network/interfaces file to make it persistent. 

**CPS Configuration**

`auto e101-001-0`
`iface e101-001-0 inet manual`
`  pre-up /bin/ip link set dev e101-001-0 up`

`auto e101-002-0`
`iface e101-002-0 inet manual`
`  pre-up sudo /bin/ip link set dev e101-002-0 up`
`  up sudo cps_config_vlan.py --add --id 1011 --vlantype 1 --port e101-001-0,e101-002-0`
`  post-up sudo /bin/ip link set dev br1011 up`

**Comment by dj-s** [comment]
@jeff-yin thank you for your time and these explanations.
@madhu222 your solution work fine, thanks !

**Comment by navalknishad** [comment]
@dj-s-- Where i suppose to enter the following lines
up sudo cps_config_vlan.py --add --id 1011 --vlantype 1 --port e101-001-0,e101-002-0
post-up sudo /bin/ip link set dev br1011 up

**Comment by GarrickHe** [comment]
@navalknishad 
In `/etc/network/interfaces`

**Comment by navalknishad** [comment]
@GarrickHe 
I have entered it the same file but its not working, When i reboot the Switch i am unable to Ping...

**Comment by madhu222** [comment]
@navalknishad  If you are configuring IP address on the bridge. Below should be your configurations.
```
auto e101-004-0
 iface e101-004-0 inet manual
 pre-up sudo /bin/ip link set dev e101-004-0 up

auto e101-003-0
 iface e101-003-0 inet manual
 pre-up sudo /bin/ip link set dev e101-003-0 up
 up sudo cps_config_vlan.py --add --id 1011 --vlantype 1 --port e101-003-0,e101-004-0
 post-up sudo /bin/ip link set dev br1011 up


auto br1011
 iface br1011 inet static
 address 19.19.19.19
 netmask 255.255.255.0
```
