### ISSUE TITLE
Result pollution in latest CPS 

### ISSUE THREAD

**Issue by kot-begemot-uk** [open-switch/opx-cps#82]
CPS now pollutes results with data from portions of the tree other than the requested one.

Example:

A request for dell-base-if-cmn/if/interfaces/interface and if/interfaces/interface/name=e101-002-0

root@uml-switch:/exports/src/IN/pycnoporus/python3-inocybe-openswitch/inocybe_openswitch# cps_get_oid.py dell-base-if-cmn/if/interfaces/interface if/interfaces/interface/name=e101-002-0

============dell-base-if-cmn/if/interfaces/interface==========

base-if-phy/if/interfaces/interface/npu-id = 0
dell-base-if-cmn/if/interfaces/interface/if-index = 4
dell-if/if/interfaces/interface/phys-address = 90:b1:1c:f4:ef:a1
dell-if/if/interfaces/interface/speed = 0
if/interfaces/interface/enabled = 0
base-if-phy/if/interfaces/interface/learn-mode = 3
if/interfaces/interface/name = e101-002-0
dell-if/if/interfaces/interface/duplex = 1
dell-if/if/interfaces/interface/auto-negotiation = 0
if/interfaces/interface/type = ianaift:ethernetCsmacd
dell-if/if/interfaces/interface/tx-idle-time = 23040
dell-if/if/interfaces/interface/oui = 6976381
dell-if/if/interfaces/interface/tx-wake-time = 23040
dell-if/if/interfaces/interface/mode = 1
base-if-phy/if/interfaces/interface/port-id = 2
dell-if/if/interfaces-state/interface/supported-speed = 3,4
dell-if/if/interfaces/interface/mtu = 1532
base-if-phy/if/interfaces/interface/phy-media = 2
dell-if/if/interfaces/interface/fec = 2
base-if-phy/if/interfaces/interface/tagging-mode = 3
dell-if/if/interfaces/interface/eee = 0
------------------------------------------------ 

The data contains dell-if/if/interfaces-state/interface/supported-speed = 3,4

It is not supposed to be there - it is in a different list in the model ietf interfaces model (brought in there by augmentations from dell-if).

**Comment by rakeshdatta** [comment]
Hi Anton,

Thanks for reaching out. I acknowledge this issue. I will get back to you with a resolution shortly. 

Thanks,
Rakesh

**Comment by rakeshdatta** [comment]
This fix is merged and would be available in the next release. Thanks!
