### ISSUE TITLE
get cps python callback never returns any data

### ISSUE THREAD

**Issue by kot-begemot-uk** [open-switch/opx-cps#97]
The root cause seems to be that the get callback in the cps core uses the same validation as the transaction code.

 _read_function in cps_api_python_operation invokes cb->execute(get) which in turn feeds the result to dict_to_cps_obj(o) from cps_api_python_utils.cpp

That has the following check:
```c++
PyObject * op = PyDict_GetItemString(dict,"operation");
    if (op!=NULL && !PyString_Check(op)) return NULL;

    cps_api_operation_types_t _op = (cps_api_operation_types_t)(0);
    if (op!=nullptr) {
        const cps_api_operation_types_t* __op = cps_operation_type_from_string(PyString_AsString(op));
        if (__op!=nullptr) _op = *__op;
    }
```
Unless I am mistaken, this check always results in NULL for a read operation as there is no "operation" dict member in this case.

As a result, the return from the get callback is always deemed invalid.

**Comment by kot-begemot-uk** [comment]
Working off incorrect example which from somewhere used TRUE instead of True in return code.

I still do not understand how it works though - according to the C++ code it should not.

**Comment by rakeshdatta** [comment]
Hi Anton,

As discussed offline, closing the issue, as you could work it out with the existing code.

For your concern regarding missing documentation on 'how to use callbacks', if you don’t find it in the OPX wiki, can you please open a documentation issue and send it across.
I will take care of it.

P.S. When you’re opening the OPX Github issue, these guidelines: https://github.com/open-switch/opx-docs/wiki/Report-bugs would help you fill up the relevant details.

Thanks,
Rakesh.
